version: '3.8'

services:
  backend:
    build:
      context: ./countries-backend/countries-api
      dockerfile: Dockerfile
    container_name: country-backend
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      - ./countries-backend:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./countries-frontend/country-app
      dockerfile: Dockerfile
    container_name: country-frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./countries-frontend/country-app:/app
      - /app/node_modules
    command: npm run dev
